ROOT: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/ScienceNOW/"
ARXIV_METADATA: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/ScienceNOW/arxivdata/arxiv-metadata-oai-snapshot.json"
ARTIFACTS: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/ScienceNOW/artifacts/trends/"
ARXIV_API_URL: "http://export.arxiv.org/api/query"
ARXIV_OAI_URL: "{http://www.openarchives.org/OAI/2.0/}"
ARXIV_OAI: "{http://arxiv.org/OAI/arXiv/}"
ARXIV_SNAPSHOT: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/arxiv-public-datasets/arxiv-data/arxiv-metadata-oai-2023-11-13.json"
EMBEDDINGS: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/arxiv-public-datasets/arxiv-data/embeddings.npy"
REDUCED_EMBEDDINGS: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/arxiv-public-datasets/arxiv-data/reduced_embeddings.npy"
FEATHER_PATH: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/arxiv-public-datasets/arxiv-data/arxiv_df.feather"
TAXONOMY_PATH: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/taxonomy.txt"
EVAL_ROOT: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/tm_evaluation/"
VOCAB_PATH: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/tm_evaluation/vocab.txt"
CORPUS_PATH: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/tm_evaluation/corpus.tsv"
SENTENCE_MODEL: "all-distilroberta-v1"
UMAP_NEIGHBORS: 15
UMAP_COMPONENTS: 5
UMAP_METRIC: "cosine"
VOCAB_THRESHOLD: 15
TM_VOCAB_PATH: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/tm_evaluation/tm_vocab.txt"
TM_TARGET_ROOT: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/tm_evaluation/"
