ROOT: "C:\\Users\\Bene\\Desktop\\ScienceNOW"
ARXIV_METADATA: "arxiv-metadata-oai-2023-11-13.json"
ARTIFACTS: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1"
ARXIV_SNAPSHOT: "arxiv-metadata-oai-2023-11-13.json"
EMBEDDINGS: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1\\embeddings.npy"
REDUCED_EMBEDDINGS: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1\\reduced_embeddings_supervised.npy"
FEATHER_PATH: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1\\arxiv_df.feather"
TAXONOMY_PATH: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1\\taxonomy.txt"
EVAL_ROOT: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1\\tm_evaluation"
VOCAB_PATH: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1\\vocab.txt"
CORPUS_PATH: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1\\tm_evaluation\\corpus.tsv"
SENTENCE_MODEL: "all-distilroberta-v1"
UMAP_NEIGHBORS: 15
UMAP_COMPONENTS: 5
UMAP_METRIC: "cosine"
VOCAB_THRESHOLD: 15
TM_VOCAB_PATH: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1\\tm_evaluation\\tm_vocab.txt"
TM_TARGET_ROOT: "C:\\Users\\Bene\\Desktop\\testfolder\\Experiments\\all-distilroberta-v1\\tm_evaluation"
PUBMED_PATH: "D:\\textds\\train\\train.txt"
PUBMED_EMBEDS: "D\\textds\\train\\pubmed.npy"
