"""empty message

Revision ID: 7480a051ab43
Revises: 72945dfe4e60
Create Date: 2023-05-30 16:06:17.832455

"""
from alembic import op
import sqlalchemy as sa
import os
import json
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "7480a051ab43"
down_revision = "72945dfe4e60"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    arxiv = op.create_table(
        "arxiv",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("title", sa.Unicode(length=800), nullable=True),
        sa.Column("arxiv_url", sqlalchemy_utils.types.url.URLType(), nullable=False),
        sa.Column("pdf_url", sqlalchemy_utils.types.url.URLType(), nullable=True),
        sa.Column("published_time", sa.DateTime(), nullable=True),
        sa.Column("authors", sa.Unicode(length=800), nullable=True),
        sa.Column("abstract", sa.Text(collation=""), nullable=True),
        sa.Column("journal_link", sa.Text(collation=""), nullable=True),
        sa.Column("tag", sa.String(length=255), nullable=True),
        sa.Column("introduction", sa.Text(collation=""), nullable=True),
        sa.Column("conclusion", sa.Text(collation=""), nullable=True),
        sa.Column("analyzed", sa.Boolean(), server_default="false", nullable=True),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", "arxiv_url"),
    )
    with open(
        os.path.join(os.path.dirname(__file__), "../data/arxiv_articles.json")
    ) as f:
        article_data = f.read()

    op.bulk_insert(arxiv, json.loads(article_data))
    op.create_table(
        "reddit_posts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("subreddit", sa.String(), nullable=True),
        sa.Column("created_utc", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "twitter_tweets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
